### ISSUE TITLE
Failures on Bazel's CI

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/rules_typescript#159]
Starting with commit 65cc4da75bcd4cb88f7dcd621da17afc29c80ff3 `//examples/testing:testing` started to fail on macOS. It has been red ever since: https://buildkite.com/bazel/rules-typescript-typescript/builds/80#15f4a0cb-0aaa-446a-a017-3fe5ee70033b

Here's the error we get. Does this at all look related to the change @alexeagle?
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
[32m01 03 2018 15:46:00.651:INFO [karma]: [39mKarma v1.7.1 server started at http://0.0.0.0:9876/
[32m01 03 2018 15:46:00.654:INFO [launcher]: [39mLaunching browser ChromeHeadless with unlimited concurrency
[32m01 03 2018 15:46:00.663:INFO [launcher]: [39mStarting browser ChromeHeadless
[33m01 03 2018 15:47:00.662:WARN [launcher]: [39mChromeHeadless have not captured in 60000 ms, killing.
[33m01 03 2018 15:47:02.664:WARN [launcher]: [39mChromeHeadless was not killed in 2000 ms, sending SIGKILL.
[33m01 03 2018 15:47:04.666:WARN [launcher]: [39mChromeHeadless was not killed by SIGKILL in 2000 ms, continuing.
```

**Comment by gregmagolan** [comment]
This is fixed with the karma fixes in PR #162. This PR switches karma to use the Chrome binary from puppeteer. @alexeagle is working on merging that in.

https://buildkite.com/bazel/rules-typescript-typescript/builds/97

**Comment by buchgr** [comment]
Awesome! thanks @gregmagolan

**Comment by buchgr** [comment]
Heya!

We are still seeing this error on macOS [1]. Any thoughts?

[1] https://storage.googleapis.com/bazel-buildkite-artifacts/d7a5dfab-0055-4534-9af4-c7981499ebf9/examples/testing/testing/attempt_1.log

**Comment by alexeagle** [comment]
I don't see why that karma test is live on CI already.
https://github.com/bazelbuild/rules_typescript/commit/3bfca0624df383e31cff697c7a07d229f9179e05 only turned on `bazel build //examples:all`

**Comment by lfpino** [comment]
Friendly ping @gregmagolan

**Comment by gregmagolan** [comment]
> We are still seeing this error on macOS [1]. Any thoughts?

@buchgr @lfpino Hey. Was on vacation. #162 is still in review. Hopefully will be merged in soon.

**Comment by buchgr** [comment]
thanks @gregmagolan !!

**Comment by gregmagolan** [comment]
#162 merged. macOS CI green https://buildkite.com/bazel/rules-typescript-typescript/builds/121
