### ISSUE TITLE
tsc_wrapped cannot find tslib when importHelpers is set to true

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_typescript#252]
I will look more into this soon. From first glance it looks like Typescript cannot resolve where 'tslib' is even if it is part of the `@//:node_modules` filegroup.

The error reported is:

```
ERROR: /private/var/tmp/_bazel_greg/34cb2c27ba201fc3e02405892697c98f/external/rxjs/BUILD.bazel:22:1: Compiling TypeScript (devmode) @rxjs//:rxjs failed (Exit 1)
external/rxjs/index.ts:73:1 - error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
```

**Comment by gregmagolan** [comment]
This is now resolved with the fix to resolveTypeReferenceDirectives (https://github.com/bazelbuild/rules_typescript/pull/259)

**Comment by robisim74** [comment]
@gregmagolan I'm still getting the error when I set `"importHelpers": true`:

```
ERROR: C:/users/simon/documents/github/angular-library-starter/BUILD.bazel:24:1: Compiling Angular templates (ngc) //:src failed (Exit 1)
src/services/sum.service.ts(3,1): error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
```

I have `tslib` added in the deps:

```
    deps = [
        "@npm//tslib",
        "@npm//@types"
    ]
```

Branch: https://github.com/robisim74/angular-library-starter/tree/bazel

Any idea?

Thanks

**Comment by gregmagolan** [comment]
@robisim74 No idea. But will re-open this so that this is not lost and take a look.
